### ISSUE TITLE
LCP Snippet not working

### ISSUE THREAD

**Issue by dajabba** [nucliweb/webperf-snippets#44]
I just copied and pasted the LCP script from the site, and I get this error message : 

Uncaught EvalError: Identifier 'dedupe' cannot be declared with 'var' in current evaluation scope, consider trying 'let' instead
    at eval (LCP:1:1)
    at JSON.parse (<anonymous>)
    at h (default~live-chat-app~live-stream-app.ad98fe07.js:2:130276)
    at h (default~live-chat-app~live-stream-app.ad98fe07.js:2:130269)
    at default~live-chat-app~live-stream-app.ad98fe07.js:2:130385

**Comment by nucliweb** [comment]
Hello @dajabba 

What is your browser and version?

**Comment by dajabba** [comment]
All good. This was a PEBKAC... I needed to reset my chrome inspector settings to default and then work back up from there to get this all to work. 

I'm unsure which Inspector settings were causing an issue .. but I had to click "restore defaults and reload", and for good measure reinstall the chrome.app from scratch.
